name: OpenCode PR Reviewer
description:
  AI-powered code review agent using OpenCode SDK for comprehensive PR analysis
author: OpenCode Team

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: check-circle
  color: blue

# Define your inputs here.
inputs:
  openrouter_api_key:
    description: 'OpenRouter API key for LLM access'
    required: true
  model:
    description:
      'LLM model to use via OpenRouter (e.g.,
      anthropic/claude-sonnet-4-20250514)'
    required: false
    default: 'anthropic/claude-sonnet-4-20250514'
  problem_score_threshold:
    description: 'Minimum score (1-10) for reporting issues'
    required: false
    default: '5'
  blocking_score_threshold:
    description:
      'Minimum score (1-10) for issues to be considered blocking and fail the
      check (defaults to problem_score_threshold)'
    required: false
    default: ''
  review_timeout_minutes:
    description: 'Total timeout for entire review in minutes (5-120)'
    required: false
    default: '40'
  max_review_retries:
    description: 'Maximum number of retry attempts if review times out (0-3)'
    required: false
    default: '1'
  enable_web:
    description: 'Enable web search and fetch capabilities'
    required: false
    default: 'false'
  github_token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  enable_human_escalation:
    description:
      'Enable escalation to human reviewers for unresolved disputes (requires
      human_reviewers)'
    required: false
    default: 'false'
  human_reviewers:
    description:
      'Comma-separated list of GitHub usernames to tag on escalated disputes
      (e.g., "alice,bob")'
    required: false
    default: ''
  debug_logging:
    description:
      'Enable verbose debug logging of LLM activity, events, and responses'
    required: false
    default: 'false'

# Define your outputs here.
outputs:
  review_status:
    description:
      'Status of the review: completed, failed, or has_blocking_issues'
  issues_found:
    description: 'Number of issues found and reported'
  blocking_issues:
    description: 'Number of blocking issues (score >= blocking_score_threshold)'

runs:
  using: node20
  main: dist/index.js
